### PR TITLE
Update Portuguese strings.po

### PR DESCRIPTION
**Pull request by sheikr**
I have no time to translate the few remaining strings so I'll push it like this if anyone wants to finish.

### CODE REVIEW

**Comment by tknorris** [comment]
Do you mind pushing this to my salts repo rather than this one? I can't use it against this one: https://github.com/tknorris/salts

**Comment by tknorris** [comment]
Also, if you are interested, there is a SALTS project on transifex that you can do the translation on: https://www.transifex.com/tv-addons/salts/dashboard/

I pull the po files from there on a regular basis.

**Comment by sheikr** [comment]
Thank you tknorris. I've created a new PR on that repo so you can close this one. Also, I'll try to update the translation on transifex asap.

**Comment by tknorris** [comment]
I think I can upload your po directly to transifex. I'm going to try that now.

**Comment by tknorris** [comment]
I uploaded your po file and transifex took it. I'm not sure if it updated the translations or not though.

**Comment by sheikr** [comment]
It did. Thanks again.

**Pull request closed without merging**
